spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/ticket_master
    user: postgres
    password:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
    name: ticket_master
    password:
    url: jdbc:postgresql://localhost:5432/ticket_master
    username: postgres


server:
  port: 8081
